### ISSUE TITLE
Double-encoded utf-8 in abstract field in META files

### ISSUE THREAD

**Issue by eserte** [jberger/Mojolicious-Plugin-RevealJS#1]
See here: https://metacpan.org/source/JBERGER/Mojolicious-Plugin-RevealJS-0.03/META.yml#L2
Which in turn looks wrong on MetaCPAN's recent page: https://metacpan.org/recent
(The Mojo-Pg-2.06 entry a few lines below looks right)

**Comment by jberger** [comment]
Argh, I've noticed this after release several times and I keep forgetting
to manually set the abstract. It seems mb cannot extract a utf8 abstract
correctly.

**Comment by jberger** [comment]
Released as 0.04. Thanks again for the reminder!
