### ISSUE TITLE
'Build test' fails for not obvious reason

### ISSUE THREAD

**Issue by charliebrady** [jberger/Mojolicious-Plugin-RevealJS#2]
+ unset DISPLAY
+ xargs --no-run-if-empty /usr/bin/perl -MExtUtils::MakeMaker -e 'MY->fixin(@ARGV)'
+ /usr/bin/perl Build.PL
+ /usr/bin/perl Build
+ /usr/bin/perl Build test
Failed to find share dir for dist 'Mojolicious-Plugin-RevealJS' at /home/speech/bradyc/rpms/BUILD/Mojolicious-Plugin-RevealJS-0.02/blib/lib/Mojolicious/Plugin/RevealJS.pm line 17
Failed 1/1 test programs. 0/0 subtests failed.

I don't know what a 'share dir' is or how I make one/buy one.

It's not even obvious to me after reading:

http://search.cpan.org/~rehsack/File-ShareDir-1.102/lib/File/ShareDir.pm

I'm just trying to package Mojolicious::Plugin::RevealJS as an rpm for installation on CentOS6 systems. I'd prefer not to need to install File::ShareDir and Class::Inspector on my build server.

Perhaps you could skip the tests that use File::ShareDir if it is not installed.

**Comment by jberger** [comment]
I have no idea what you are doing here. I don't use EUMM at all and the reveal.js files are all bundled using File::ShareDir. Without it, it might install, but it won't work correctly. I suppose you could get the reveal.js stuff via CDN (is there one?) but it wouldn't work offline, which is something most presenters want to have; conference WIFI is often unreliable.

**Comment by jberger** [comment]
Ah, so the problem really is that File::ShareDir is not in the prereqs. Sorry about that. I'll fix that.

**Comment by charliebrady** [comment]
On Thu, 11 Jun 2015, Joel Berger wrote:

> Ah, so the problem really is that File::ShareDir is not in the prereqs. 
> Sorry about that. I'll fix that.

That's an issue, but that's not the issue I am reporting here. Without 
File::ShareDir, 'Build test' fails due to File::ShareDir not being found. 
You've apparently fixed that now - although it's perhaps debatable whether 
File::ShareDir is required when you only use it in a test script.

With File::ShareDir installed, 'Build test' fails in the way shown in the 
original post:

 Failed to find share dir for dist 'Mojolicious-Plugin-RevealJS' 

I don't know what that means or how to correct it.

[ExtUtils::MakeMaker isn't relevant to this issue - it just happens to be 
there because cpan2rpm puts it in the build script. It's a NOOP here.]

**Comment by jberger** [comment]
> although it's perhaps debatable whether
File::ShareDir is required when you only use it in a test script.

It is not only required for testing. All of these files will be unavailable without File::ShareDir https://github.com/jberger/Mojolicious-Plugin-RevealJS/tree/master/lib/Mojolicious/Plugin/RevealJS/files

I cannot replicate your problem, so I'm not sure where to take things from here.
